# Basic configuration settings for the project

title: Health Super App
description: A single place for patients with Inflammatory Bowel Disease (IBD) to contact their healthcare practitioners, manage their disease activity, and track their medication.
baseurl: "/"

# Jekyll settings
markdown: kramdown
theme: jekyll-theme-cayman  # Updated theme (choose from GitHub Pages-supported themes)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# GitHub Pages settings
github:
  is_project_page: false  # Set to true if this is a project page
  actions_enabled: true  # Enable GitHub Actions for Jekyll builds

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Additional settings
highlighter: rouge  # Syntax highlighting
paginate: 5  # Number of posts per page
paginate_path: "/page:num/"
